import { UserRole } from "@/lib/prisma/enums"

export const ROLES = {
  FACULTY_ADMIN: "FACULTY_ADMIN",
  DEPARTMENTAL_OFFICER: "DEPARTMENTAL_OFFICER",
  LECTURER: "LECTURER",
  COURSE_REP: "COURSE_REP",
} as const

export type Role = UserRole

// Permission definitions based on comprehensive permissions matrix
export const PERMISSIONS = {
  // User Management
  MANAGE_ALL_USERS: [ROLES.FACULTY_ADMIN],
  MANAGE_DEPARTMENTAL_STAFF: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  ASSIGN_ROLES: [ROLES.FACULTY_ADMIN],
  
  // Dashboard & Overview
  VIEW_ALL_DEPARTMENTS_SUMMARY: [ROLES.FACULTY_ADMIN],
  VIEW_DEPARTMENTAL_STATISTICS: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  VIEW_PERSONAL_REQUESTS: [ROLES.LECTURER, ROLES.FACULTY_ADMIN],
  VIEW_ASSIGNED_ASSETS: [ROLES.LECTURER, ROLES.FACULTY_ADMIN],
  VIEW_AVAILABLE_CONSUMABLES: [ROLES.COURSE_REP, ROLES.LECTURER, ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  
  // Asset Registration & Categorization
  REGISTER_ASSETS: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  APPROVE_ASSET_REGISTRATIONS: [ROLES.FACULTY_ADMIN],
  DEFINE_ASSET_CATEGORIES: [ROLES.FACULTY_ADMIN],
  CATEGORIZE_ASSETS: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  VIEW_ALL_ASSETS: [ROLES.FACULTY_ADMIN, ROLES.DEPARTMENTAL_OFFICER],
  
  // Asset Assignment / Allocation
  OVERSEE_ALL_ALLOCATIONS: [ROLES.FACULTY_ADMIN],
  ASSIGN_ASSETS: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  RECEIVE_ASSIGNED_ASSETS: [ROLES.LECTURER, ROLES.FACULTY_ADMIN],
  
  // Barcode / QR Generation
  AUTHORIZE_BARCODE_TEMPLATES: [ROLES.FACULTY_ADMIN],
  GENERATE_BARCODES: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  
  // Asset Request (Borrowing)
  MONITOR_ALL_REQUESTS: [ROLES.FACULTY_ADMIN],
  APPROVE_REQUESTS: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  CREATE_REQUEST: [ROLES.LECTURER, ROLES.COURSE_REP, ROLES.FACULTY_ADMIN],
  
  // Asset Return / Verification
  REVIEW_RETURN_SUMMARIES: [ROLES.FACULTY_ADMIN],
  VERIFY_RETURNS: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  RETURN_ASSETS: [ROLES.LECTURER, ROLES.FACULTY_ADMIN],
  
  // Transfer Management
  APPROVE_INTER_DEPARTMENTAL_TRANSFERS: [ROLES.FACULTY_ADMIN], // Legacy - kept for backward compatibility
  APPROVE_TRANSFERS: [ROLES.FACULTY_ADMIN], // All transfers must be approved by Faculty Admin
  INITIATE_TRANSFERS: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN], // Only officers can initiate transfers
  
  // Maintenance Management
  REVIEW_MAINTENANCE_BUDGET: [ROLES.FACULTY_ADMIN],
  REVIEW_MAINTENANCE_LOGS: [ROLES.FACULTY_ADMIN],
  RECORD_MAINTENANCE: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  SCHEDULE_MAINTENANCE: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  REPORT_ASSET_FAULTS: [ROLES.LECTURER, ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  
  // Consumable Management
  OVERSEE_STOCK_SUMMARIES: [ROLES.FACULTY_ADMIN],
  MANAGE_CONSUMABLES: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  UPDATE_CONSUMABLE_QUANTITIES: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  REQUEST_CONSUMABLES: [ROLES.LECTURER, ROLES.COURSE_REP, ROLES.FACULTY_ADMIN],
  
  // Expiry / Stock Alerts
  RECEIVE_ALL_ALERTS: [ROLES.FACULTY_ADMIN],
  RECEIVE_DEPARTMENTAL_ALERTS: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  RECEIVE_RETURN_REMINDERS: [ROLES.LECTURER, ROLES.FACULTY_ADMIN],
  
  // Notifications & Messaging
  SEND_SYSTEM_WIDE_ALERTS: [ROLES.FACULTY_ADMIN],
  COMMUNICATE_WITH_STAFF: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  RECEIVE_NOTIFICATIONS: [ROLES.LECTURER, ROLES.COURSE_REP, ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  
  // Reports & Analytics
  GENERATE_GLOBAL_REPORTS: [ROLES.FACULTY_ADMIN],
  GENERATE_DEPARTMENTAL_REPORTS: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  VIEW_REQUEST_HISTORY: [ROLES.LECTURER, ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  VIEW_USAGE_HISTORY: [ROLES.LECTURER, ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  GENERATE_REPORTS: [ROLES.FACULTY_ADMIN, ROLES.DEPARTMENTAL_OFFICER],
  VIEW_REPORTS: [ROLES.FACULTY_ADMIN, ROLES.DEPARTMENTAL_OFFICER, ROLES.LECTURER],
  
  // Audit Trail
  VIEW_ALL_SYSTEM_LOGS: [ROLES.FACULTY_ADMIN],
  VIEW_DEPARTMENTAL_LOGS: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  VIEW_OWN_ACTIVITY_HISTORY: [ROLES.LECTURER, ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  
  // Backup & Recovery
  INITIATE_BACKUP_RECOVERY: [ROLES.FACULTY_ADMIN],
  
  // System Settings
  CONFIGURE_GLOBAL_PARAMETERS: [ROLES.FACULTY_ADMIN],
  CONFIGURE_DEPARTMENTAL_DATA: [ROLES.DEPARTMENTAL_OFFICER, ROLES.FACULTY_ADMIN],
  
  // Security & Permissions
  MANAGE_ALL_PERMISSIONS: [ROLES.FACULTY_ADMIN],
  MANAGE_SECURITY_SETTINGS: [ROLES.FACULTY_ADMIN],
} as const

export function hasPermission(role: Role, permission: keyof typeof PERMISSIONS): boolean {
  const allowedRoles = PERMISSIONS[permission]
  return (allowedRoles as readonly string[]).includes(role)
}

export function hasAnyPermission(role: Role, permissions: Array<keyof typeof PERMISSIONS>): boolean {
  return permissions.some(permission => hasPermission(role, permission))
}

export function hasAllPermissions(role: Role, permissions: Array<keyof typeof PERMISSIONS>): boolean {
  return permissions.every(permission => hasPermission(role, permission))
}

